### ISSUE TITLE
Scaffolder is using Surfacer methods

### ISSUE THREAD

**Issue by creadicted** [SnoringCatGames/scaffolder#3]
Hey!
in `annotation_element.gd` the method `_draw_from_surface` uses the Surface class which is not part of the  Scaffolder addon but part of Surfacer.  
https://github.com/SnoringCatGames/scaffolder/blob/65fe56f0497c2496ceb76a0f5a3a11fa69a29798/src/annotators/annotation_element.gd#L39

Similar to `profiler.gd` 
where in `stop_with_optional_metadata` the class `EdgeCalcResultMetadata` is used. 
https://github.com/SnoringCatGames/scaffolder/blob/2cced62cc51fd5c907801d52b68ef4c8ff7427c8/src/utils/time/profiler.gd#L76

**Comment by levilindsey** [comment]
Thanks! I try to keep these references from creeping in, but I don't have a good mechanism for that right now, other than occasional manual checks (I develop these two repositories simultaneously from within the same Godot project). I'll clean those up soon.

**Comment by levilindsey** [comment]
Ok, I think I should have removed all of the dependencies on Surfacer from Scaffolder!

And I created a new repo to make sure that Scaffolder is working when Surfacer isn't present: https://github.com/SnoringCatGames/scaffolder-bootstrap

Thanks again for filing the bug!
