### ISSUE TITLE
Question about Debouncer implementation

### ISSUE THREAD

**Issue by BruceLiCong** [SnoringCatGames/scaffolder#4]
https://github.com/SnoringCatGames/scaffolder/blob/ff3035b2aa2bf1d4602609257936629ff91be64b/src/utils/time/_debouncer.gd#L42

I'm wondering why not return immediately after triggering the callback, the callback will be triggered twice if the on call haven't been invoked in the interval. Is it the internal behavior?

**Comment by levilindsey** [comment]
Oh, nice catch! You are correct, we don't want that to trigger the callback twice in that case if the debounce was only triggered once.

I just submitted a small change ([ef78541](https://github.com/SnoringCatGames/scaffolder/commit/ef78541f5ad58fa9e3efafe21124b475a1c01c2b)) that should fix this.

Thanks for commenting on this!

**Comment by BruceLiCong** [comment]
Cool, thanks for confirming!
